[package]
name = "http-r-server"
version = "0.1.0"
edition = "2021"
authors = ["Qua Is X qua.is.kyiv.ua@gmail.com"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
